### ISSUE TITLE
Write unit tests for meta-stuff with sk-learn compatibility

### ISSUE THREAD

**Issue by brookehus** [scikit-time/scikit-time#10]
e.g. pipelines, gridsearch

Collection of sklearn tools that should be supported with our estimates (best would be to have a parameterized test for this, estimators x tools):

- [x] pipelines (implemented for a special case)
- [ ] grid search (other CV methods?)

**Comment by clonker** [comment]
CV methods are not robustly realizable due to the implementation in sklearn
