### ISSUE TITLE
Make docs and developer guidelines

### ISSUE THREAD

**Issue by brookehus** [scikit-time/scikit-time#11]
i.e. resources for contributors and users

- [x] issue templates
- [x] PR templates
- [x] installation guide (to some degree there, needs instructions on how to install via conda/pip)
- [x] contributing guide
- [x] user documentation

**Comment by clonker** [comment]
somewhat connected to #36

**Comment by clonker** [comment]
consider using https://github.com/mkdocs/mkdocs
