### ISSUE TITLE
[ENH] fit_predict in BaseClassifier

### ISSUE THREAD

**Issue by patrickzib** [scikit-time/scikit-time#112]
The `BaseClassifier` has a method called `fit_predict`: 
https://github.com/scikit-time/scikit-time/blob/0b05e134b5873034bffa272ff5f96fc81bcf20d7/sktime/classification/base.py#L259

It trains the model and does the prediction using the same data.

I am not aware of something similar for supervised learners in sklearn, e.g.:
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

Also, I could not find any usages of the `fit_predict()` method in the code, too.

My suggestion: remove `fit_predict`?

**Comment by TonyBagnall** [comment]
perhaps consider in conjunction with this?

**Comment by patrickzib** [comment]
To underline:

The same functionality is present in sklearn, called `cross_val_predict`, and has a much simpler api:
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_predict.html

Here is a check, that is gives the same results:
```python
    X_train, y_train = load_gunpoint(split="train", return_type="numpy2d")

    # train weasel
    weasel = WEASEL(random_state=0)
    weasel.fit(X_train, y_train)
    predictions1 = weasel.fit_predict(X_train, y_train, cv=5)
    print("Sktime Predictions\n", predictions1)

    from sklearn.model_selection import cross_val_score
    score = cross_val_score(WEASEL(random_state=0), X_train, y_train, cv=5)
    print("Sklearn Score", score)

    from sklearn.model_selection import cross_val_predict
    predictions2 = cross_val_predict(WEASEL(random_state=0), X_train, y_train, cv=5)
    print("Sklearn Predictions:\n", predictions2)
    print("Predictions Equal:\n", (predictions2 == predictions1).all())
```

> [...]
> Predictions Equal: True
