### ISSUE TITLE
[BUG] Remove duplicate function in classification/tests/test_base.py

### ISSUE THREAD

**Issue by TonyBagnall** [scikit-time/scikit-time#119]
somehow, we have written the same function twice :) They are both used so pick one, change the uses and get rid of the other. 
(unless I am missing something @MatthewMiddlehurst )
![image](https://user-images.githubusercontent.com/9594042/221429836-6e8c2c05-b5cb-4909-ab8d-712d0aed5f9d.png)

**Comment by scorcism** [comment]
Hello there,
I'm willin to work of this issue

**Comment by TonyBagnall** [comment]
great, thanks, go for it, any questions, just ask

**Comment by scorcism** [comment]
Whose code block shoud I remove ?

**Comment by scorcism** [comment]
I have removed the Tony Bagnall one, coz Mathew has nice comment with the function.
Shall I make a PR ?

**Comment by TonyBagnall** [comment]
thats fine, please do make a PR

**Comment by TonyBagnall** [comment]
be warned, the CI takes a looooong time, we are working on it :)

**Comment by scorcism** [comment]
ohh okay

**Comment by scorcism** [comment]
I have made the PR
