### ISSUE TITLE
[BUG] `NumbaDistance` is potentially slow: Numba recompiles closures upon every call

### ISSUE THREAD

**Issue by patrickzib** [scikit-time/scikit-time#141]
I tried to profile Elastic Ensemble to find out why it is so slow in CI.

I suspect the following: There seems to be an issue with numba and nested functions (called closures). Unfortunately, Numba complies the nested function upon every call: 

https://github.com/numba/numba/issues/1810
https://github.com/pola-rs/polars/issues/5872

This causes numba to recompile, i.e. the DTW `numba_dtw_distance()` closure, every time it is invoked. 
**That means for every pair of time series, the closure is compiled first.**

https://github.com/scikit-time/scikit-time/blob/6fd4a729b047ff7974823e1cab6bcd7d3b66b4d2/sktime/distances/_dtw.py#L193
```python
 def _distance_factory(
              [....]
    ) -> DistanceCallable:
         [....]
        @njit(cache=True)
        def numba_dtw_distance(
            _x: np.ndarray,
            _y: np.ndarray,
        ) -> float:
            cost_matrix = _cost_matrix(_x, _y, _bounding_matrix)
            return cost_matrix[-1, -1]

        return numba_dtw_distance
```

I do not have an instant solution for this, but it is a huge bottleneck.

**Comment by patrickzib** [comment]
WHhile profiling, it seems like 90% of the runtime is spent compiling:
<img width="130" alt="image" src="https://user-images.githubusercontent.com/7783034/222537267-30856807-cf1a-435b-ba22-9b87d32ec06c.png">

**Comment by patrickzib** [comment]
Compile is called 4200 times: 
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/7783034/222538967-4352f234-fcce-4e28-9ef9-2962fefe6bdf.png">

**Comment by TonyBagnall** [comment]
I think this is a problem, I thought it was solved previously. One solution we had was to use the distance factory, which builds once I think. @chrisholder can comment much better than me

from sktime.distances import distance_factory

        if isinstance(self.distance, str):
            if self.distance_params is None:
                self.metric_ = distance_factory(X[0], X[0], metric=self.distance)
            else:
                self.metric_ = distance_factory(
                    X[0], X[0], metric=self.distance, **self.distance_params
                )

**Comment by patrickzib** [comment]
Unfortunately, this doesn't Factory seem to be working. In EE the `KNeighborsTimeSeriesClassifier`is called, which uses the factory. Still, the Distance-Closure is compiled over and over.

**Comment by TonyBagnall** [comment]
ah ok, I think @chrisholder has ideas/a solution
