### ISSUE TITLE
should clustering even be here?

### ISSUE THREAD

**Issue by brookehus** [scikit-time/scikit-time#21]
@psolsson pointed out that clustering is not a time-series algorithm. Should it be removed?

**Comment by marscher** [comment]
IMO it should, because state space discretization of arbitrary time series is required for MSM building. Of course we can demand users to use another package for this purpose, but is it convenient?

**Comment by marscher** [comment]
We can also ship clustering (later) as a separate package, but this would also involve more maintenance overhead on which we agreed keeping it low.
