### ISSUE TITLE
PCCA and ReactiveFlux should not be Estimators

### ISSUE THREAD

**Issue by franknoe** [scikit-time/scikit-time#35]
They do not use data but models or even just transition matrices as input. I don't see why they should be regarded as an estimator. It seems unnatural to do first a construction without the model they depend on but already use definitions of A, B sets (for TPT) which depends on the model that is only provided later with .fit(model).

So I think these are maybe "models" if there is any use for that, but they are outside the usual "estimator" logic.

**Comment by marscher** [comment]
This is a follow up on #19.
I agree to your concern, it seemed strange to uncouple them from the original model.

So the computation of the Model should happen in the MSM then.
