### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by franknoe** [scikit-time/scikit-time#36]
As far as I can see the code is undocumented unless docs were available from PyEMMA. All new code, especially the user API needs to be documented with the same standard.

**Comment by marscher** [comment]
Did we agree on a user-api yet? To the best of my knowledge we said that sktime is a collection of estimators like scikit-learn.

**Comment by clonker** [comment]
consider using pydantic

**Comment by clonker** [comment]
I believe this is the case now. Otherwise feel free to reopen
