### ISSUE TITLE
[FORK] Replace sponsor info

### ISSUE THREAD

**Issue by TonyBagnall** [scikit-time/scikit-time#4]
remove the sponsor this project info

![image](https://user-images.githubusercontent.com/9594042/216441216-5b04a343-dd74-4866-9fca-b8690b54df48.png)

**Comment by TonyBagnall** [comment]
@MatthewMiddlehurst I think you have fixed this? Can we close?

**Comment by MatthewMiddlehurst** [comment]
Old info is removed but theres nothing to replace it currently.

**Comment by TonyBagnall** [comment]
ok, I'll close this as the immediate task has been done
