### ISSUE TITLE
[ENH] Deprecate the alignment module

### ISSUE THREAD

**Issue by TonyBagnall** [scikit-time/scikit-time#46]
The alignment module wraps a package called dtw-python which contains an implementation of dtw that is slower than our ours.  The functionality of alignment is available in distances using our own distance functions. The only place it is used is in KNN, which I would like to remove
https://github.com/scikit-time/scikit-time/issues/47
https://github.com/scikit-time/scikit-time/issues/39
and dists_kernels, which I would also like to deprecate. @chrisholder

**Comment by MatthewMiddlehurst** [comment]
Use #79
