### ISSUE TITLE
[ENH] Parallel Backend

### ISSUE THREAD

**Issue by patrickzib** [scikit-time/scikit-time#61]
Should we change the parallel backend to threading in the classifiers?

```python
Parallel(n_jobs=n_jobs, backend="threading")(
```

I have noticed issues when calling nested Parallel-constructs.

@MatthewMiddlehurst @TonyBagnall I recall, you noticed similarly?

**Comment by TonyBagnall** [comment]
yes we had issues. Matthew may remember better than me, but I think it tends to time slice and pickle, which can cause permission issues, and that changing the backend to threading ameliorated it. I did not get to the bottom of it, there is a fair amount to do with threading classifiers imo, but we should default to backend threading imo

**Comment by patrickzib** [comment]
Thus, we could change it for all classifiers? Or maybe make it a parameter of each classifier?

**Comment by TonyBagnall** [comment]
I would choose to hard code it for each classifier, I don't think it really needs exposing as a parameter. Having said that, I do not have a full grasp on the ramifications. Testing/benchmarking the parallel is on my (long) list. So perhaps change classifiers where its an issue, run some experiments pre and post with those to make sure its better and correct, and leave the policy change until we can properly evaluate it across the board

**Comment by MatthewMiddlehurst** [comment]
I think we should eventually expose it as a parameter, but just hardcode threading for now. This has solved multithreading issues in the past.

**Comment by patrickzib** [comment]
Has been solved with recent commit
