### ISSUE TITLE
[BUG] failed test test_softdeps.py::test_est_fit_without_modulenotfound[TEASER]

### ISSUE THREAD

**Issue by TonyBagnall** [scikit-time/scikit-time#68]
**Describe the bug**
changing some docs has opened a can of worms it seems.  

sktime/tests/test_softdeps.py::test_est_fit_without_modulenotfound[TEASER] - KeyError: 0
====== 1 failed, 1204 passed, 1 skipped, 30 warnings in 93.89s (0:01:33) =======
make: *** [Makefile:40: test_softdeps] Error 1

so it fails test_est_fit_without_modulenotfound for some reason.  I'm guessing, but this is testing whether Teaser throws module not found when built without the correct soft dependency? Seems slow for the dictionary classifiers,
<img width="579" alt="image" src="https://user-images.githubusercontent.com/9594042/219070357-1200a958-5abf-4190-b81a-344a0163adf8.png">

another example of the completely OTT testing see #59, its like the test suite is meant to be an oracle that can spot all possible bugs. This is just unrealistic and impractical imo  

**To Reproduce**

](https://github.com/scikit-time/scikit-time/actions/runs/4184490173/jobs/7250212056)
**Expected behavior**

This is how it fails

<img width="524" alt="image" src="https://user-images.githubusercontent.com/9594042/219070996-67edebe4-7615-4bb2-b65e-de3f8dde925b.png">

it is imo a problem with the test not the classifier, I will look closer. 
**Versions**
<details>

</details>

**Comment by TonyBagnall** [comment]
I am not willing to dig into why this particular test is causing this problem. I have wasted a lot of time in the past figuring out why test config breaks code, but for now I think it best to just exclude them

**Comment by patrickzib** [comment]
It tests TEASER with Catch22. I suppose Catch22 requires a soft-dependency

**Comment by TonyBagnall** [comment]
I'm going to close this issue for now, since it is a tiny speck of sand in the desert of testing issues. The excluded estimators and tests list is very large!
