### ISSUE TITLE
[BUG] Early Classifier changes

### ISSUE THREAD

**Issue by TonyBagnall** [scikit-time/scikit-time#69]
generally need to look at EarlyClassification. There is a deprecation warning

<img width="618" alt="image" src="https://user-images.githubusercontent.com/9594042/219216933-aed1257a-6814-40a8-a626-b8c891123356.png">

not sure if we still want to do this, and also TEASER is failing some classification tests, due we think to my refactoring of _class_dictionary in the Classifier base class.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/9594042/219104603-aa9bfac9-56f0-4244-b3ad-90b5885cca22.png">

see this PR for more info

https://github.com/scikit-time/scikit-time/pull/52
excluded TEASER because of global test failures
https://github.com/scikit-time/scikit-time/issues/68

@patrickzib

**Comment by patrickzib** [comment]
I was able to trace it down: you refactored `_class_dictionary` to `class_dictionary` but forgot to make the change it in TEASER:

https://github.com/scikit-time/scikit-time/blob/a2cb64a832eca754597d7971301fb9e291512d8a/sktime/classification/early_classification/_teaser.py#L400

**Comment by patrickzib** [comment]
Might be worth checking all other classifiers, too, if there is still some `_class_dictionary`

**Comment by TonyBagnall** [comment]
ah ok, early classifiers a bit different, and refactoring in pycharm a bit shit! thanks, will track it down tomorrow

**Comment by TonyBagnall** [comment]
I'll just revert my refactoring, it was purely superficial and not really necessary
