### ISSUE TITLE
[FORK] Update the landing page

### ISSUE THREAD

**Issue by TonyBagnall** [scikit-time/scikit-time#7]
I think we should remove all of this 
https://github.com/scikit-time/scikit-time/blob/main/README.md
for now, and just have a simple message "This is a fork of sktime made by previous core developers, and is a work in progress" or something.  Any thoughts on that?

**Comment by MatthewMiddlehurst** [comment]
Currently, uses a disclaimer, still needs to be updated with new links.

**Comment by TonyBagnall** [comment]
I'll close this if no one minds. The landing page is currently stable, and further changes will be more specific than this and relate to name etc, so are in my mind a separate issue.
