### ISSUE TITLE
Default random engine might be linear congruential

### ISSUE THREAD

**Issue by chrisfroe** [scikit-time/scikit-time#78]
Was browsing through the code and found this

https://github.com/scikit-time/scikit-time/blob/b6f9a9e910d83d2e4c84ece6e3540371c26d17dd/sktime/src/include/distribution_utils.h#L31

The `std::default_random_engine` potentially has a "very short" period.

Reminded me of this https://github.com/readdy/readdy/issues/180#issuecomment-616358967

**Comment by clonker** [comment]
Argh you are completely right, I should have thought of this. Matter of habit. Thanks! :rocket:

**Comment by clonker** [comment]
Exchanged by the Mersenne tonguetwister
