### ISSUE TITLE
[ENH] Deprecate the alignment module

### ISSUE THREAD

**Issue by TonyBagnall** [scikit-time/scikit-time#79]
**Is your feature request related to a problem? Please describe.**

The alignment module was introduced with no clear demand. It introduced a new soft dependency, dtw-python, rather than use our own implementations. There is a whole infrastructure of base class etc, but there are no examples I can see.  The functionality 
"computes the full alignment between X[0] and X[1]" is available in the distances module as follows. 

```python
from sktime.distances import dtw_alignment_path
x = np.random.rand(10)
y = np.random.rand(10)
path=dtw_alignment_path(x, y)
print(path)

from sktime.distances import distance_alignment_path
path2=distance_alignment_path(x, y, metric="dtw")
print(path)
```

I dont think there is anyone here who wants to maintain this. 

The only place it is used is the dists_kernels module in the class DistFromAligner, which itself is not used anywhere. In my view, distances or alignments between time series should be found by calling distance functions which can return alignments if required. If you want a distance matrix/kernel for a set of time series, call the pairwise_distances function. That is how it is done in distances. This is how other packages provide distances. In Aligner and dist_kerns there is a confusing set of things such as "Composer that creates distance from aligner." 

**Describe the solution you'd like**
I want to delete the director alignment and the class DistFromAligner

**Describe alternatives you've considered**
An alternative would be to attempt to merge it with dist_and_kerns and distances. I do not want to do this

**Additional context**

these are the only usages of this module. There are no docs related to it I can see. It should be simple to get rid of it. 

![image](https://user-images.githubusercontent.com/9594042/219715029-e41478f9-c907-45cb-9a3b-0c3a495abd52.png)

**Comment by chrisholder** [comment]
I never saw a use for this module as the distances module already has a API which is so much better and easier to use as Tony mentions. The module was designed with the intent that functions would be used. The design was inspired by scipys distance module which is one of the most used and in my opinion the best:
https://docs.scipy.org/doc/scipy/reference/spatial.distance.html

The design exposes a single function where you can pass the data (x and y) with a metric parameter that is a string name for the distance you want to use. In addition, there are individual function for each distance/alignment that contains the documentation for the distance and another option for users to use the module.

 So for dtw (and you can swap in any of our distances) this was the design (before it was wrapped in classes):

```
from sktime.distances import dtw_alignment_path, distance, distance_alignment_path, dtw_distance
x = np.random.rand(10)
y = np.random.rand(10)

distance_with_metric = distance(x, y, metric="dtw")
distance_with_func = dtw_distance(x, y)

alignment_with_metric = distance_alignment_path(x, y, metric="dtw")
alignment_with_func = dtw_alignment_path(x, y)
```
