### ISSUE TITLE
msm refactor design

### ISSUE THREAD

**Issue by clonker** [scikit-time/scikit-time#8]
In pyemma there is no separation between model and estimator in the msm part.

In order to create such a separation and make code more readable / maintainable, we have to decide where exactly to cut.

In general there is statistics about the input dtrajs as well as the count matrix. This can, e.g., be captured in a separate `TransitionCountEstimator` - `TransitionCountModel` pair.

A MSM in principle does not need to be estimated from data but can be constructed from a transition matrix `P`. In that case there would be a `MarkovStateModel` instance.
If however the MSM is estimated from data, a `TransitionCountModel` is intermediately needed and the attributes are probably still interesting for further evaluation.

The question is how to most conveniently combine these two models into one.

1. One could make use of multiple inheritance, i.e., `class EstimatedMarkovStateModel(MarkovStateModel, TransitionCountModel)`.
2. Composition: The `EstimatedMarkovStateModel` is a glorified tuple of the `MarkovStateModel` and `TransitionCountModel`
3. The `MarkovStateModel` has a (default `None`) reference to a `TransitionCountModel`
4. General restructure: The base model is defaulted to `None` and only exists within an estimator once it has been fitted.

**Comment by clonker** [comment]
on a related note: i propose to change `dt_dtraj` to something more descriptive like `discrete_time_unit`

**Comment by marscher** [comment]
#9 has implemented 3.
