### ISSUE TITLE
[ENH] Deprecate Python 3.7 and bump scikit-learn version

### ISSUE THREAD

**Issue by aiwalter** [scikit-time/scikit-time#84]
Some estimators dont support Python 3.7 anymore, we should think about deprecating it. Also newer `scikit-learn>=1.1.0` has no Python 3.7 anymore.

Probably we can bump then `scikit-learn>=1.1.0` and possibly also other dependencies to require a higher version.

**Comment by MatthewMiddlehurst** [comment]
#71 I agree we can remove it, but don't see a need to deprecate.

**Comment by aiwalter** [comment]
Yeah I meant remove

**Comment by MatthewMiddlehurst** [comment]
Assumed so but just wanted to check, I think it's a good idea.
