### ISSUE TITLE
[ENH] Elastic Ensemble is slow

### ISSUE THREAD

**Issue by patrickzib** [scikit-time/scikit-time#97]
Elastic Ensemble takes 7 minutes in CI on python 3.7, win32:

> 235.27s call  sktime/classification/tests/test_all_classifiers.py::TestAllClassifiers::test_classifier_on_unit_test_data
> 195.10s call     sktime/classification/distance_based/_elastic_ensemble.py::sktime.classification.distance_based._elastic_ensemble.ElasticEnsemble

<img width="956" alt="image" src="https://user-images.githubusercontent.com/7783034/220330769-95c9c613-20cd-4a56-81c6-d1430f2d21ef.png">

Can we, i.e., change default-parameters?

**Comment by TonyBagnall** [comment]
thanks for raising this, I noticed it too. One issue is that it is building the numba functions, and that has to happen somewhere. Another is the set up, which could be faster for interface testing and for the correctness, which I will look at.

**Comment by patrickzib** [comment]
Is there something wrong with CI?

If I check locally the whole test_all_classifiers.py takes just <2 minutes.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/7783034/220332903-16d25362-834b-4b79-9bc5-6b46c9df4bee.png">

On CI the single test takes 235 s

**Comment by patrickzib** [comment]
@TonyBagnall, @chrisholder 

What is the purpose of

```python
def to_numba_timeseries(x: np.ndarray) -> np.ndarray:
   [...]
   _x = np.array(x, copy=True, dtype=float) 
   [...]
```

It copies the input data before every distance measure comparison. This seems to be rather inefficient?

**Comment by patrickzib** [comment]
Also this is performed on every call to a distance computation, as I understand it?
